version: 2
updates:
  - package-ecosystem: pip
    directory: /main/kivo-server
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
