"""Robot events: the typed vocabulary and the in-process bus that carries it."""

from robot.events.bus import DEFAULT_QUEUE_SIZE, EventBus, EventHandler, Subscription
from robot.events.types import (
    ActionFinished,
    AgentTurnCompleted,
    AgentTurnFailed,
    AgentTurnStarted,
    ActionStarted,
    ActionSubmitted,
    BatteryUpdated,
    CapabilitiesRefreshed,
    EmergencyStopChanged,
    MotionCompleted,
    MotionFailed,
    PoseUpdated,
    RobotConnected,
    RobotDisconnected,
    RobotEvent,
    SensorUpdated,
    SpeechInterrupted,
    SpeechRequested,
    TelemetryUpdated,
    ToolCallCompleted,
    ToolCallFailed,
    ToolCallRefused,
    ToolCallStarted,
    ToolDiscovered,
)

__all__ = [
    "DEFAULT_QUEUE_SIZE",
    "ActionFinished",
    "AgentTurnCompleted",
    "AgentTurnFailed",
    "AgentTurnStarted",
    "ActionStarted",
    "ActionSubmitted",
    "BatteryUpdated",
    "CapabilitiesRefreshed",
    "EmergencyStopChanged",
    "EventBus",
    "EventHandler",
    "MotionCompleted",
    "MotionFailed",
    "PoseUpdated",
    "RobotConnected",
    "RobotDisconnected",
    "RobotEvent",
    "SensorUpdated",
    "SpeechInterrupted",
    "SpeechRequested",
    "Subscription",
    "TelemetryUpdated",
    "ToolCallCompleted",
    "ToolCallFailed",
    "ToolCallRefused",
    "ToolCallStarted",
    "ToolDiscovered",
]
